# Generated by Django 5.1.4 on 2026-06-12 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=200)),
                ('chapter', models.CharField(max_length=200)),
                ('question_id', models.CharField(max_length=200)),
                ('question_type', models.CharField(choices=[('SCQ', 'Single Choice Question'), ('MCQ', 'Multiple Choice Question'), ('Numerical', 'Numerical'), ('PYQ', 'Previous Year Question')], default='SCQ', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(default=1)),
                ('selected_answer', models.CharField(blank=True, max_length=200)),
                ('is_correct', models.BooleanField()),
                ('time_taken_secs', models.PositiveIntegerField(default=0)),
                ('mistake_type', models.CharField(blank=True, choices=[('Conceptual', 'Conceptual'), ('Procedural', 'Procedural'), ('Calculation', 'Calculation'), ('Misinterpretation', 'Misinterpretation')], max_length=50, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-attempted_at',),
            },
        ),
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_study_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyImprovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=200)),
                ('score_7d_ago', models.PositiveSmallIntegerField(default=0)),
                ('score_now', models.PositiveSmallIntegerField(default=0)),
                ('delta', models.IntegerField(default=0)),
                ('week_start', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_improvements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-week_start', '-delta'),
            },
        ),
        migrations.CreateModel(
            name='ConceptProficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=200)),
                ('chapter', models.CharField(max_length=200)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('correct_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('flat', 'Flat')], default='flat', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_proficiencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('concept_name',),
                'unique_together': {('user', 'concept_name')},
            },
        ),
        migrations.CreateModel(
            name='DailyProficiencySnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('avg_score', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_proficiency_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date',),
                'unique_together': {('user', 'chapter', 'date')},
            },
        ),
    ]
